export enum ErrorCode {
  // Auth Errors
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",
  AUTH_NETWORK_ERROR = "AUTH_NETWORK_ERROR",

  // Payment Errors
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_CANCELLED = "PAYMENT_CANCELLED",
  PAYMENT_INVALID_AMOUNT = "PAYMENT_INVALID_AMOUNT",

  // API Errors
  API_NETWORK_ERROR = "API_NETWORK_ERROR",
  API_RATE_LIMIT = "API_RATE_LIMIT",
  API_SERVER_ERROR = "API_SERVER_ERROR",

  // Generic Errors
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // RevenueCat Errors
  REVENUECAT_OFFERING_UNAVAILABLE = "REVENUECAT_OFFERING_UNAVAILABLE",
  REVENUECAT_PACKAGE_UNAVAILABLE = "REVENUECAT_PACKAGE_UNAVAILABLE",
  REVENUECAT_PURCHASE_FAILED = "REVENUECAT_PURCHASE_FAILED",
  REVENUECAT_PAYWALL_ERROR = "REVENUECAT_PAYWALL_ERROR",

  // Auth Specific Errors
  AUTH_APPLE_SIGNIN_FAILED = "AUTH_APPLE_SIGNIN_FAILED",
  AUTH_GOOGLE_SIGNIN_FAILED = "AUTH_GOOGLE_SIGNIN_FAILED",
  AUTH_EMAIL_SIGNIN_FAILED = "AUTH_EMAIL_SIGNIN_FAILED",
  AUTH_SIGNOUT_FAILED = "AUTH_SIGNOUT_FAILED",
  AUTH_DELETE_ACCOUNT_FAILED = "AUTH_DELETE_ACCOUNT_FAILED",
  AUTH_NO_USER_DATA = "AUTH_NO_USER_DATA",
  AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING",
  AUTH_INVALID_REDIRECT = "AUTH_INVALID_REDIRECT",

  // Login Screen Errors
  LOGIN_GOOGLE_SIGNIN_CANCELLED = "LOGIN_GOOGLE_SIGNIN_CANCELLED",
  LOGIN_APPLE_SIGNIN_CANCELLED = "LOGIN_APPLE_SIGNIN_CANCELLED",
  LOGIN_BROWSER_ERROR = "LOGIN_BROWSER_ERROR",
  LOGIN_PRIVACY_POLICY_ERROR = "LOGIN_PRIVACY_POLICY_ERROR",

  // Stripe API Errors
  STRIPE_SESSION_ERROR = "STRIPE_SESSION_ERROR",
  STRIPE_PAYMENT_INTENT_ERROR = "STRIPE_PAYMENT_INTENT_ERROR",
  STRIPE_CUSTOMER_ERROR = "STRIPE_CUSTOMER_ERROR",
  STRIPE_AUTHORIZATION_ERROR = "STRIPE_AUTHORIZATION_ERROR",
  STRIPE_REQUEST_ERROR = "STRIPE_REQUEST_ERROR",
  STRIPE_REQUEST_TIMEOUT = "STRIPE_REQUEST_TIMEOUT",

  // Profile Image Errors
  PROFILE_IMAGE_UPLOAD_FAILED = "PROFILE_IMAGE_UPLOAD_FAILED",
  PROFILE_IMAGE_FETCH_FAILED = "PROFILE_IMAGE_FETCH_FAILED",
  PROFILE_IMAGE_PICKER_FAILED = "PROFILE_IMAGE_PICKER_FAILED",
  PROFILE_IMAGE_URL_INVALID = "PROFILE_IMAGE_URL_INVALID",
  PROFILE_IMAGE_TOO_LARGE = "PROFILE_IMAGE_TOO_LARGE",
  PROFILE_IMAGE_FORMAT_INVALID = "PROFILE_IMAGE_FORMAT_INVALID",

  // Database Errors
  DB_PROFILE_CREATE_FAILED = "DB_PROFILE_CREATE_FAILED",
  DB_PROFILE_FETCH_FAILED = "DB_PROFILE_FETCH_FAILED",
  DB_PROFILE_UPDATE_FAILED = "DB_PROFILE_UPDATE_FAILED",
  DB_PROFILE_NOT_FOUND = "DB_PROFILE_NOT_FOUND",
  DB_OPERATION_FAILED = "DB_OPERATION_FAILED",
  DB_FEEDBACK_SUBMIT_FAILED = "DB_FEEDBACK_SUBMIT_FAILED",
}

export interface AppError {
  code: ErrorCode;
  message: string;
  originalError?: any;
  metadata?: Record<string, any>;
}
